def generate(_data):
    msg = "deliberately broken generate function"
    raise Exception(msg)
